spring:
  # 指定Tomcat端口
  port: 8089
  application:
    name: glyxybxxtthtd-bxd
  cloud:
    alibaba:
      seata:
        #自定义事务组名称需要与seata-server中的对应
        tx-service-group: fsp_tx_group
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/glmc?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

#eureka的yml配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
  instance:
    prefer-ip-address: true



mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.edu.guet.bean
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8089
  tomcat:
    max-http-form-post-size: 80000000

logging:
  level:
    cn.edu.guet.mapper: DEBUG